config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "messages#index"
  namespace :messages do
    resources :searches, only: :index
  end
  resources :messages do
    resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user

  validates :text, {presence: true, length: {maximum: 140}}

  mount_uploader :image, ImageUploader
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :text, {presence: true, length: {maximum: 300}}

  def self.search(search)
    return Message.all unless search
    Message.where('text LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :comments

  validates :nickname, :email, presence: true, length: { maximum: 8 }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/messages/#{comment.message.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :image).merge(user_id: current_user.id, message_id: params[:message_id])
  end
end

app/controllers/messages/searches_controller.rb
class Messages::SearchesController < ApplicationController
  def index
   @messages = Message.search(params[:keyword])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @messages= Message.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @message = Message.new
  end

  def create
    Message.create(message_params)
  end

  def edit
  end

  def update
    message = Message.find(params[:id])
    message.update(message_params)
  end

  def show
   @comment = Comment.new
   @comments = @message.comments.includes(:user)
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
  end
  private
  def message_params
    params.require(:message).permit(:image, :text).merge(user_id: current_user.id)
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @messages = user.messages.order("created_at DESC").page(params[:page]).per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages/searches_helper.rb
module Messages::SearchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoryLine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header__top">
        <a href="/"><%= image_tag 'logo1.png', class: "header__top__left" %></a>
        <% if user_signed_in? %>
          <div class="header__top__right">
            <span><%= current_user.nickname %>
            <%= link_to "My-page", "/users/#{current_user.id}", class: "registration" %>
            <%= link_to "Log-out", destroy_user_session_path, class: "registration", method: :delete %>
            </span>
            <%= link_to  "New-Post", "/messages/new", class: "post" %>
          </div>
        <% else %>
          <div class="header__top__right">
            <%= link_to "Sign-up", new_user_registration_path, class: 'registration' %>
            <%= link_to "Log-in", new_user_session_path, class: 'registration' %>
          </div>
        <% end %>
        </div>
      </div>
      <div class= "header__navbar">
        <%= form_with(url: messages_searches_path, local: true, method: :get, class: "search-form") do |form| %>
          <%= form.text_field :keyword, placeholder: "Searching words", class: "search-input" %>
          <%= form.submit "Search", class: "search-btn" %>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form.text_field :image, class: "text-image", placeholder: "Image URL", id: "image" %>
<%= form.text_area :text, placeholder: "Text: less than 300", rows: "3", id: "text" %>
<%= form.submit "Send", class: "btn" %>

app/views/messages/_message.html.erb
    <div class="content__image" style="background-image: url(<%= message.image%>);">
      <span class="content__image__name">
        <a href="/users/<%= message.user.id %>">
          <span>Poster : </span><%= message.user.nickname %>
        </a>
      </span>
      <div class="action">
        <ul class="action_list">
          <span><%= image_tag 'arrow_top.png' %></span>
          <li>
            <%= link_to 'Detail', "/messages/#{message.id}", method: :get %>
          </li>
          <% if user_signed_in? && current_user == message.user_id%>
          <li>
            <%= link_to '..Edit..', "/messages/#{message.id}/edit", method: :get %>
          </li>
          <li>
            <%= link_to 'Delete', "/messages/#{message.id}", method: :delete %>
          </li>
          <% end %>
        </ul>
      </div>
     <div class="content__text">
      <%= simple_format(message.text) %>
    </div>

app/views/messages/create.html.erb
<div class = "contents">
  <div class = "wrapper">
    <div class = "done" >
      <h3>
        DONE
      </h3>
      <a class = "btn-back" href = "/messages">Back to top-page</a>
    </div>
  </div>
</div>

app/views/messages/destroy.html.erb
<div class = "contents">
  <div class = "wrapper">
    <div class = "done" >
      <h3>
        DONE
      </h3>
      <a class = "btn-back" href = "/">Back to top-page</a>
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<div class = "contents">
  <div class = "container">
    <%= form_with(model: @message, local: true) do |form| %>
      <h3>
        EDIT
      </h3>
      <%= render partial: "form", locals: { form: form} %>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<div class="contents">
  <% @messages.each do |message| %>
    <%= render partial: "message", locals: { message: message } %>
  <% end %>
  <%= paginate(@messages)%>
</div>

app/views/messages/new.html.erb
<div class = "contents">
  <div class = "container">
    <%= form_with(model: @message, local: true) do |form| %>
      <h3>
        POST
      </h3>
      <%= render partial: "form", locals: { form: form} %>
    <% end %>
  </div>
</div>

app/views/messages/searches/index.html.erb
<div class="contents">
  <% @messages.each do |message| %>
    <%= render partial: "messages/message", locals: { message: message } %>
  <% end %>
</div>

app/views/messages/show.html.erb
<div class="shows">
  <div class="show__image" style="background-image: url(<%= @message.image%>);">
    <span class="show__image__name">
      <a href="/users/<%= @message.user.id %>">
      <span>Poster : </span><%= @message.user.nickname %>
      </a>
    </span>
    <% if user_signed_in? && current_user.id == @message.user.id %>
      <div class="action">
        <ul class="action_list">
          <span><%= image_tag 'arrow_top.png' %></span>
          <li>
            <%= link_to '..Edit..', "/messages/#{@message.id}/edit", method: :get %>
          </li>
          <li>
            <%= link_to 'Delete', "/messages/#{@message.id}", method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    <div class="show__text">
    <%= simple_format(@message.text) %>
    </div> 
  </div> 
  <div class="comment">
    <% if current_user %>
      <%= form_with(model: [@message, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "Comment: less than 140", rows: "3" %>
        <%= form.file_field :image, class: "comment-image", placeholder: "Image URL" %>
        <%= form.submit "Comment - Send", class: "comment-btn" %>
      <% end %>
    <% else %>
      <div class="strong">
      <strong><p>You need to "Sing-up" or "Log-in" for posting some comments</p></strong>
      </div>
    <% end %>
      <div class="comments">
      <h4>＜Comments - Line＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p class="comment-box">
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
            <img src="<%= comment.image%>">
        <% end %>
      <% end %>
  </div>
</div>

app/views/messages/update.html.erb
<div class = "contents">
  <div class = "wrapper">
    <div class = "done" >
      <h3>
        DONE
      </h3>
      <a class = "btn-back" href = "/messages">Back to top-page</a>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="posts">
  <p class="post-list">Post - List of..... "<%= @nickname %>".....</p>
  <% @messages.each do |message| %>
    <div class="post__image" style="background-image: url(<%= message.image%>);">
      <span class="post__image__name">
        <a href="/users/<%= message.user.id %>">
          <span>Poster : </span><%= message.user.nickname %>
        </a>
      </span>
      <div class="action">
        <ul class="action_list">
          <span><%= image_tag 'arrow_top.png' %></span>
          <li>
            <%= link_to 'Detail', "/messages/#{message.id}", method: :get %>
          </li>
          <li>
            <%= link_to '..Edit..', "/messages/#{message.id}/edit", method: :get %>
          </li>
          <li>
            <%= link_to 'Delete', "/messages/#{message.id}", method: :delete %>
          </li>
        </ul>
      </div>
     <div class="post__text">
      <%= simple_format(message.text) %>
    </div>
  <% end %>
  <%= paginate(@messages)%>
</div>